### ISSUE TITLE
broken inclusion of model in .png files as string

### ISSUE THREAD

**Issue by nbehrnd** [openbabel/openbabel#2428]
- [X] I believe this to be a bug with Open Babel

## Environment Information
Open Babel version:  3.1.1
Operating system and version:  Linux Debian 12/bookworm [testing], Python 3.9.8

## Expected Behavior

According to `obabel -L png`, it is possible to append/include e.g., the mol file to/in the `.png` written. See e.g., legacy  documentation of OpenBabel 2.3.1 [here](http://openbabel.org/docs/current/FileFormats/PNG2_format.html) and comment by @frederikw in issue report [here](https://github.com/openbabel/openbabel/issues/2426).

## Actual Behavior

Observation: The `.png` are written and are intelligible.  By report of the CLI, the inclusion of the structure file however fails.

Suggested changes, 1st class:
+ Bug fix to restore the functionality.
+ Addition of an explicit entry in the current version of the program documentation.

Suggested changes, 2nd class:
+ With the `.pngj` format ([documentation](http://wiki.jmol.org/index.php/File_formats/Export)), Jmol apparently offers a similar export of static (classical `.png` like) and interactive (model) data.  In Jmol, it is possible, e.g., to read this extended `.png`, to interact and export the model as `.sdf` «as usual».  See archive  pngj_examples.zip for examples.  It would be nice if Jmol's `.pngj` would be understood by OpenBabel, and the augmented `.png` written by OpenBabel could be read by Jmol as in «accessing the model data».

## Steps to Reproduce

```bash
$ obabel -:"CC(=O)Cl" -O mymol.png -xO smi
==============================
*** Open Babel Error  in PNG Format
  Not a PNG file
==============================
*** Open Babel Error  in PNG Format
  Failed to embed molecule(s)
1 molecule converted
```
The image is written and intelligible.  The subsequent attempt to recover the SMILES string from the `.png` however fails, and file `smiles.txt` stays empty.

```bash
$ obabel mymol.png -osmi -O smiles.txt
==============================
*** Open Babel Error  in PNG Format
  Not a PNG file
1 molecule converted
```

[example_pngj.zip](https://github.com/openbabel/openbabel/files/7521417/example_pngj.zip)

**Comment by fredrikw** [comment]
The actual bug should be fixed in the PR above. I have not touched the documentation.

**Comment by nbehrnd** [comment]
@fredrikw The functionality in question already was described (section 18.8.2, or [here](https://open-babel.readthedocs.io/en/latest/FileFormats/PNG_2D_depiction.html)), thus I retracted one suggestion.

Regarding the possible exchange of augmented `.png` with Jmol's `.pngj` format
> «PNGJ has become the de facto standard file format or many J(S)mol users.»
>
> [Jmol Wiki](http://wiki.jmol.org/index.php/File_formats/Compressed)

do you perceive it were of great benefit («cross pollination») of the communities of OpenBabel and Jmol, thus justifying to be kept as a midterm desideratum?

**Comment by fredrikw** [comment]
It's not apparent from the Jmol documentation how the pngj format is constructed. But looking at the supplied file suggests that it is too dissimilar to the OpenBabel png format to be easily adapted. Instead it should probably be a separate format and I do not know how big the overlap is.

**Comment by emmamcintosh** [comment]
I'm still seeing this error (not a PNG file) even though I've downloaded the newest version of open babel

**Comment by fredrikw** [comment]
The newest released version or the dev master? I don't think there has been a release after this fix.

**Comment by emmamcintosh** [comment]
i have the latest version (3.1.1.1) - I installed using brew

**Comment by fredrikw** [comment]
It's been a long while since I used Homebrew, but I think you could use `brew install open-babel --HEAD` to get the current GitHub head.
